export const topicActions = {
  GET_TOPIC_DETAIL: 'GET_TOPIC_DETAIL',
  COLLECT_OR_DE_COLLECT: 'COLLECT_OR_DE_COLLECT',
  POST_REPLY_UPS: 'POST_REPLY_UPS',
  POST_NEW_REPLY: 'POST_NEW_REPLY',
};
export const topicMutations = {
  SET_TOPIC_DETAIL: 'SET_TOPIC_DETAIL',
  DELET_TOPIC_DETAIL: 'DELET_TOPIC_DETAIL',
};
export const TopicModule = 'topic';
